travis:
  secure:
    BINSTAR_TOKEN: LX5LHT9i3pPoovCILfwq2HVr/q9ty1wQHSNu9ppUECyW3uiQ9XETeKwTc0AFTfuSYbPv9hJOSor+GL4gdUPst3TKPLtpTh/8vBHCYzGditSw62SK0Ajg7pnC/OYwV+7rEbf0LiRukzrTzjnbjBB0elZE8sUcvoHvph/4VOODpugv5kFohI/R1H5x5UP041oelpUyg/jNAcZGWsR11mjwhzyy8fL335CIr23zpQvCTn+mv+mys6eayNYU0rejyMPbQpN5OFGgMS0ltFQd4W0pAqnrlKzbvmOXj0YVT7CNAzkOLDLylH4Urih2/9tSGZ23NngrbinDvpxeyexU6V0YF6s9fEV3drmzgxE0CS/laiaKCEdpFWpfy9zxxONMkQyTTNJQSdw1JoUvNjbWaUMvkTCEL5z/wPdJqIV7vj+3FLRzIW3xKkfU01YZiNxMnK9OrVL8nvqMeBSpm7rh4Ntt+Fh+7+oqZzxVNztcDl8Fn2o0Ccsrupa/ctWdr1jiWNtdikHMu9bV5VVPGquNPlsoLDTAlb0G7oAaHZd/Exm/huWzddl9WfSVrHgqYKC1xaOYPvzfQrjyYrJLe4WRMNojT73m4lpR151LtQb5J4z7uzi+fbqF273H3ZSItF00xPtjB/FkZhjZz359sTlREgc1FB3wFfj6oUGD0uKjiPrvVrk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
